version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
